import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { poppins } from "@/lib/Fonts";
import { ThemeProvider } from "@/components/themeProvide";

export const metadata: Metadata = {
	title: "Aman Verma | Full-Stack Developer",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${poppins.variable} font-poppins antialiased`}>
				<ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
					<header className="fixed top-0 w-full z-10 h-20 backdrop-blur-md shadow-md">
						<Navbar />
					</header>
					<main className="pt-24">{children}</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
